### ISSUE TITLE
Better handling of JSON serialization of large integers

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#153]
Right now, the JSON serialization output for bigints sometimes uses strings and sometimes uses ints. This isn't a problem when working in Python3, since all ints are bigints. The rest of the world isn't so pleasant. If we want our structures to play nicely in JavaScript and elsewhere, we should make sure that ElementModP and ElementModQ always serialize to strings.

**Comment by keithrfung** [comment]
This is a python repository so changed the title to ensure we specify what is happening without mentioning specific types in other languages. 

The `int` in python allows for larger integers than other languages. To allow the serialized outputs to be used elsewhere. A string output would be preferable since the other languages can cast to the appropriate type for larger integers.

**Comment by keithrfung** [comment]
For electionguard in cpp, there was a lot of discussion around converting these to hex on serialization. I'm going to close out #155 in favor of moving discussion here.

**Comment by pamtaro** [comment]
I took a look at the changes in PR #154 and it's not directly related to the hex changes I have in my fork - https://github.com/microsoft/electionguard-python/compare/main...pamtaro:feature/hex_hashes

So these serializaiton changes will address how the bignum representation is deserialized out from Python's base10 bignum to a base64 string, but what my hex changes are doing is converting how a bignum (in the form of bytes) will be serialized _in_ to the hash functions (since we're only hashing strings anyway). The use of hex as the string input to represent a bignum will need to be consistent with how the C++ hash functions also represent a bignum during these hashing steps. Because C++ does not have a bignum representation built-in, we're unable to use a base10 bignum representation (like python) without a lot of work to convert the binary to a custom bignum object or pulling in a 3rd party library. However, hex is easy to convert to from a binary in any language (and also easy to convert back into a binary), so instead of using a string representation of the base10 bignum, we just convert the binary to it's hex representation.

Although these 2 changes (in PR #154 and in my fork) are independent of each other (we can have both changes), having the output bignum in base64 but the hashing function's input bignum in base16 (hex) might be confusing (if a dev is working on both sides of the code). So we will probably want to just choose 1 of them going forward.

**Comment by danwallach** [comment]
If you look at my PR for base64 encoding (https://github.com/microsoft/electionguard-python/pull/154), what you'll see is that I did a cutoff. Anything smaller than some arbitrary constant, in this case 100 million, is rendered in JSON as a base-10 "number". Anything bigger is rendered as a base64 "string". That difference is handy because you don't want to base64 encode all the small numbers that show up everywhere as sequence numbers for ballots, contests, selections, and so forth.

Also handy if you're on an old crappy machine where `int` is 32 bits and you don't want your lame JSON library to freak out with integer overflow.

**Comment by danwallach** [comment]
For your hashing needs, you could "serialize" to JSON then feed that string into the hasher.
