### ISSUE TITLE
Possible error in generating extended_crpyto_hash

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#279]
In writing a validator for the specification "3. Election Public-Key Validation":

````
(A) Q̅ = H(Q, K 1,0 , K 1,1 , K 1,2 , ... , K 1,k−1 , K 2,0 , K 2,1 , K 2,2 , ... , K 2,k−1 , ... , K n,0 , K n,1 , K n,2 , ... , K n,k−1 )
(B) K = ∏ ni=1 K i mod p.
````

Which I understand to mean that the extended_crpyto_hash Q̅ has "all of the public guardian commitments 𝐾𝑖,𝑗  hashed together"

However in election.py lines starting at 899:

    crypto_base_hash = hash_elems(
        P, Q, G, number_of_guardians, quorum, description_hash
    )
    crypto_extended_base_hash = hash_elems(crypto_base_hash, elgamal_public_key)

Which I think means that only the Guardian's public keys are used, ie:

````
Q̅ = H(Q, K 1,0 , K 2,0 ... , K n,0 )
Q̅ = H(Q, K)
````

**Comment by JohnLCaron** [comment]
So the question is for @benolah or another crypo expert, as to whether Q̅ should / must have all of the commitments in it, and to the python implementors if the omission was deliberate, and if so why. If its inadvertent, I can submit a PR.

**Comment by benaloh** [comment]
I think that ALL of the commitments should be included in the base hash -- mostly according to the principal that including more stuff doesn't hurt.

I'll add, however, that I don't see an obvious threat that arises from leaving out these commitments because they are really just about the guardians negotiations with each other and there is an effective mechanism to deal with disagreements amongst guardians.  Therefore, while I think that they should be included, it's not a high priority to do so.

**Comment by AddressXception** [comment]
@benaloh given your [comment on #278](https://github.com/microsoft/electionguard-python/issues/278#issuecomment-774199884) do you think we should still include the commitments as part of the `crypto_extended_base_hash`?

One way to implement this would be to calculate :
```
commitment_hash = H(K 1,0 , K 1,1 , K 1,2 , ... , K 1,k−1 , K 2,0 , K 2,1 , K 2,2 , ... , K 2,k−1 , ... , K n,0 , K n,1 , K n,2 , ... , K n,k−1 )
```

when we execute the key ceremony and propagate the result and cache it.  We can then modify our uses of `ElectionJointKey` like so:

```python
#instead of
ElectionJointKey = ElementModP

#we can redefine like so:
class ElectionJointKey(NamedTuple):
    joint_public_key: ElementModP
    commitment_hash: ElementModQ
```

and then we:

```python
Q̅ = H(Q, K, commitment_hash)
```

In practice, this should only be in one place: when we call `make_ciphertext_election_context` to generate the `crypto_extended_base_hash` since that object propagates through all of the API's.  It does however mean that both of these properties are tightly linked.

**Comment by benaloh** [comment]
Yes, and my apologies for muddling threads #278 and #279.

I think that it would be good to include ALL of the key commitments (including the key share commitments) in the extended base hash (as described above).  The perf isn't onerous as this hash is computed just once by EG per election and once per verifier per election.

**Comment by AddressXception** [comment]
ok great, so for clarity, we'll make the change in #279 to include the commitments as part of the calculation of the `crypto_extended_base_hash`.  #278 will be closed as `WONT_FIX` and instead the specification will be adjusted so that schnorr proofs do not include the `crypto_base_hash` in their calculation and guardians are not explicitly coupled to an election (but an election is still explicitly coupled to a set of guardians.

**Comment by AddressXception** [comment]
@benaloh one more thing i want to clarify.  in the current python code the extended base hash is calculated like so:

```python
# The Base Hash and the public key
Q̅ = H(Q, K)
```

but in my example above i was intending to calculate it like so:

```python
# the base hash, the public key, _and_ the coefficient commitments
Q̅ = H(Q, K, commitment_hash)
```

however the spec is written as:

```python
# the base hash and the coefficient commitments
Q̅ = H(Q, commitment_hash)
```

should i include the joint public key in the calculation of the crypto extended base hash (and update the spec to reflect that), or should it be implemented as the spec is written, excluding the joint public key?

**Comment by JohnLCaron** [comment]
Im going to assume the correct answer is 

````
Q̅ = H(Q, commitment_hash)
````
where
````
commitment_hash = H(K 1,0 , K 1,1 , K 1,2 , ... , K 1,k−1 , K 2,0 , K 2,1 , K 2,2 , ... , K 2,k−1 , ... , K n,0 , K n,1 , K n,2 , ... , K n,k−1 )
````

**Comment by benaloh** [comment]
Honestly, it doesn't matter much.  The usual rule is to throw everything into the hash on the theory that it's best to lock everything down rather than risk missing something.  However, in this case, the election public key K is very directly determined by the by the individual guardian public keys which are already included in the commitment hash.  So there is really no need to spend the additional cycles -- as minimal as they are.  Since there is no reason to change things, I suggest just leaving the code and spec as is.
