### ISSUE TITLE
test_end_to_end_election writes spoiled_ballots twice into the election record.

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#290]
When publishing, **tests/integration/test_end_to_end_election.py** writes all ballots into the **encrypted_ballots** directory, and then the spoiled ballots into the **spoiled_ballots** directory.

I think it should only write cast ballots into **encrypted_ballots**, theres no obvious reason to write spoiled ballots twice. Theres no spec that I know of, and this is the only example of how to write the election record.

**Comment by keithrfung** [comment]
The spoiled ballots should be the decrypted spoiled ballots. This is relevant.

**Comment by JohnLCaron** [comment]
Makes sense that the spoiled ballots should be written as decrypted (plaintext) to the **spoiled_ballots** folder, rather than as encrypted, since those are already in **encrypted_ballots**. If I have that right, ill change my code to do that.

**Comment by JohnLCaron** [comment]
Yes of course, the spoiled ballots are part of the hash chain.

**Comment by JohnLCaron** [comment]
It appears that the information is stored in _Tally.PlaintextTally.spoiled_ballots_, and that the decrypted spoiled ballots  are not needed to be stored separately in the spoiled_ballots directoy.

**Comment by JohnLCaron** [comment]
Im looking at this issue with respect to scalability when the number of ballots gets large.

in PlaintextTally (tally.py, line 177):

    spoiled_ballots: Dict[BALLOT_ID, Dict[CONTEST_ID, PlaintextTallyContest]]

So, for each spoiled ballot there is a PlaintextTally (= the collection of PlaintextTallyContests) which is the tally for just that ballot. This grows linearly with the number of spoiled ballots. Other than this field, PlaintextTally does not depend on the number of ballots.

I wonder if these should be moved to a separate "spoiled ballots" directory, which can then be read iteratively, instead of having to read all spoiled ballot tallies at once in the PlaintextTally serialization. This may have been the original intent, but mistakenly the encrypted spoiled ballot was written, instead of the tally, (even though it is already in the ballots directory).

This is all to support Verification spec #12 Decryption of spoiled ballots:

"Every ballot spoiled in an election is individually verifiably decrypted in exactly the same way
that the aggregate ballot of tallies is decrypted. Election verifiers should confirm all such
decryptions so that casual observers can simply view the decryptions and confirm that they
match their expectations."

Is there a reason to store a PlaintextTally rather than the spoiled ballot's decrypted PlaintextBallot?. Is the "casual observer" the person who spoiled the ballot?

So here are concrete questions:

1. Do we agree that we should store a PlaintextTally for each spoiled ballot, instead of the decrypted PlaintextBallot?

2. What do you think about putting the PlaintextTally (or PlaintextBallot) into the spoiled_ballots directory in the election record, rather than inside the elections's PlaintextTally?

**Comment by keithrfung** [comment]
1. This is actually a concern that I'm handling in #205 . 
2. This is exactly the concern that led to the files starting with `Published` because we need to isolate the spoiled ballots. I think there will be a larger fix will be needed to isolate this. 

The problem directly surrounds what we consider a "Tally"

Currently,
`CiphertextTally` has `cast` and `spoiled`
`PlaintextTally` has `contests` and `spoiled_ballots` where `spoiled_ballot` is also a set of `PlaintextTallyContest`s

These need to get adjusted to:
`CiphertextTally` -> encrypted tally with `contests`
`ciphertext_spoiled_ballots` -> list of `CiphertextAcceptedBallot`

`PlaintextTally` -> decrypted tally with `contests`
`plaintext_spoiled_ballots` -> list of `PlaintextTally`

I'm gonna close this issue since it overlaps with #205
