### ISSUE TITLE
hashing doesn't correctly handle some corner cases

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#378]
## Issue

**Description**
In experimenting with my "educational" version of ElectionGuard, where I accumulated the whole formula of every operation on ElementModP and Q, I discovered a few misfeatures in the hash function.

- If the value being hashed is the integer 0, that's treated by Python as "false" and is hashed as "null"
- There were some cases where lists weren't being hashed recursively, but were instead being converted to a string and then hashed as a string

None of these impact correctness, since the hash still properly depends on the value in question, but they do impact portability, in the sense that another programming language might properly implement the same hash function with identical behavior. 

The patch is pretty simple, only a few changes in `hash.py`

**Comment by danwallach** [comment]
This turned out to break some unit tests that checked for the specific weird behavior of the old hash function. I've now adjusted the tests to be consistent with the new behavior.

**Comment by axman6** [comment]
I've also been trying to implement hashing in another language, and am finding the way that hashes work in this repo quite odd.

The decision to treat hash_elems with three arguments differently to hash_elems with a three-tuple with the same three elements seems odd to me. I had assumed that the final hash would be constructed from all the values contributing to the hash separated by "|", but in cases where the input is a sequence, we have to compute the hash of that whole structure.
 What I would have expected was something like the following (which is untested, my python is pretty rusty)

```python

def hash_elems(*a: CRYPTO_HASHABLE_ALL) -> ElementModQ:
    """
    Given zero or more elements, calculate their cryptographic hash
    using SHA256. Allowed element types are `ElementModP`, `ElementModQ`,
    `str`, or `int`, anything implementing `CryptoHashable`, and lists
    or optionals of any of those types.

    :param a: Zero or more elements of any of the accepted types.
    :return: A cryptographic hash of these elements, concatenated.
    """
    h = sha256()
    h.update("|".encode("utf-8"))
    for x in a:
        hash_update_elems(h,x)

    # We don't need the checked version of int_to_q, because the
    # modulo operation here guarantees that we're in bounds.
    return int_to_q_unchecked(int.from_bytes(h.digest(), byteorder="big") % Q_MINUS_ONE)

def hash_update_elems(h,*a: CRYPTO_HASHABLE_ALL) -> ElementModQ:
    """
    Given zero or more elements, calculate their cryptographic hash
    using SHA256, updating a given hash context. Allowed element types
    are `ElementModP`, `ElementModQ`, `str`, or `int`, anything
    implementing `CryptoHashable`, and lists or optionals of any of
    those types.

    :param h: A SHA256 context
    :param a: Zero or more elements of any of the accepted types.
    :return: A cryptographic hash of these elements, concatenated.
    """

    for x in a:
        # We could just use str(x) for everything, but then we'd have a resulting string
        # that's a bit Python-specific, and we'd rather make it easier for other languages
        # to exactly match this hash function.

        if not x:
            # This case captures empty lists and None, nicely guaranteeing that we don't
            # need to do a recursive call if the list is empty. So we need a string to
            # feed in for both of these cases. "None" would be a Python-specific thing,
            # so we'll go with the more JSON-ish "null".
            hash_me = "null"

        elif isinstance(x, (ElementModP, ElementModQ)):
            hash_me = x.to_hex()
        elif isinstance(x, CryptoHashable):
            hash_me = x.crypto_hash().to_hex()
        elif isinstance(x, str):
            # strings are iterable, so it's important to handle them before the following check
            hash_me = x
        elif isinstance(x, Sequence):
            # The simplest way to deal with lists, tuples, and such are to crunch them recursively.
            hash_update_elems(h,*x)
            hash_me = nil
        else:
            hash_me = str(x)

        if hash_me: h.update((hash_me + "|").encode("utf-8"))
```

Doing this would mean that hashing something like `[1,(2,3),[(4,5),6]` would be equivalent to performing a hash over the single string`|01|02|03|04|05|06|` rather than some somewhat arbitrary choice of returning the result of `|01|<hash of (2,3) in hex>| <hash of <hash of (3,4)>, 6>|`

What I'm not sure about is how important the structure is in the hashes being constructed, but I wouldn't have thought this were particularly important.

**Comment by danwallach** [comment]
You raise an interesting question. The current design is recursive. So if it hits something that's crypto-hashable, you (likely) get another "hash" header. Should a tuple be flattened (new behavior) or treated like a list or iterable (processed recursively)? I'll argue that recursion is a consistent solution.

What language are you working in? My Kotlin version is currently targeted at student projects, so it only has low-level primitives, not all the high level ballot abstractions.

**Comment by danwallach** [comment]
One justification for the recursive structure is that it gets us out of subtle cryptographic gotchas, where two things we're hashing that have different shapes might flatten to the same sequence of inputs to the hash function. That seems microscopically likely to actually occur in the real world, but security paranoia says that we shouldn't leave a time bomb sitting in our hash function for future generations to trip over.

**Comment by axman6** [comment]
Yeah I did think about what you happen if you happened to have the same sequence of hashable items in different structures, but I can't see this would be easily exploited, you still need to be able to produce the same hashable items, which is what the hash is supposed to check anyway. The problem comes when using languages which don't have variadic functions, where multiple arguments would be passed in using tuples, and the handling of these functions would be different depending on if this is the top level call or a recursive one.

**Comment by danwallach** [comment]
Hmm. Varargs definitely makes the common-case usage of `hash_elems` cleaner than it might otherwise. 

If you don't have varargs, then I suppose you could define it as taking a list (or tuple or whatnot), which means that the top-level iterates through the list, and if it finds another list, it becomes recursive.

**Comment by axman6** [comment]
I took your advice and I've decided to use a type of S-Expressions, that should give me what's needed to match the behaviour here.

**Comment by axman6** [comment]
I think I finally got an implementation that works in a similar way to the python implementation, but some of the decisions are just bizarre. I see no reason why the integer `0` should be hashed as the string `null` instead of the sensible `00`. Relying on the truthiness of python in the specification seems like it;'s just asking for problems, particularly when porting to other languages. And with the above integer issue, I would argue that the python implementation doesn't meet the specification.

I would also really like to see some unit tests that have exact values that are expected for example hashes - I'm getting the following for a hash of the ElementModQ `1`, but have no idea if that matches the expected value: `ElementMod 40677219090659355057937666039608240739439661729487310312972515788410031365428`.

**Comment by rc-ms** [comment]
Thanks for this thread and discussion. We hope to address this immediately after our next release. We plan to enable a suite of more efificient unit tests with prescriptive values such as you indicate.

**Comment by axman6** [comment]
Thanks @rc-ms, I'm looking forward to seeing it. Do you have any indication of roughly how far away that is likely to be?

**Comment by AddressXception** [comment]
> Thanks @rc-ms, I'm looking forward to seeing it. Do you have any indication of roughly how far away that is likely to be?

We are pulling this in to the current iteration.
