### ISSUE TITLE
🧮  Revisit BaseElement, ElementModQ, ElementModP

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

`ElementModQ` and `ElementModP` sit at the base of many of numbers and serve as a bounded integer that most of the math uses. There have been concerns raised around the inheritance from an `int`. 

A large part of this concern is the possibility for a developer to use `ElementModQ` or `ElementModP` in typical `int` math functions and exceed the lower or higher bound without knowing it. The math functions supplied in the library won't run into this issue, but since the `+` or `*` operator can be used on an `int`, it could arise. 

For example: A developer could harmlessly do:
```py
a = ElementModQ(MAX_Q)
b = 1
c = a + b # should exceed max
```
Instead of using the math functions we supply such as `add_q`. 

### Possible Implementation

There are two possible solutions, both will require a significant amount of tests.

**1. Override existing math functions**
Ensure any typical math functions can't be used so that when a developer is using `ElementModP` and `ElementModQ` it will catch any numbers that exceed the bounds. 

The most concerning ones that are concerning are add, mult, subt, and pow. 
https://docs.python.org/3/library/math.html
https://diveintopython3.net/special-method-names.html

**2. Turn BaseElement into a Number class**
This can mean making an abstract Number class or simply just providing all the methods in BaseElement. 
Essentially this means making a custom number class that serializes like an `int`. 
https://www.python.org/dev/peps/pep-3141/

It may be wise to at this juncture to also implement `__ceil__` and `__floor__` instead of lower and upper bound. 

#### Math

This case requires significant testing. Here are a list of suggestions. 

Breaking the ceiling:
```py
should_break = ElementModQ(MAX_Q) + 1 
should_also_break = 1 + ElementModQ(MAX_Q)
```

Breaking the floor:
```py
should_break = ElementModQ(0) - 1 
should_also_break = 0 - ElementModQ(1)
```

These should be thorough and test different variations of ElementModP and ElementModQ while interacting with `int` and other common math functions. 

#### Serialization

We want to ensure there is no serialization code in the base `electionguard` repository. This is to give flexibility to other developers who may choose to use our library differently. 

Currently our `electionguard-api-python` uses FastAPI thus pydantic. Pydantic like other json serialization tools uses `asdict` to ensure that an object can be serialized as plain Javascript object. Similarly, we have many other developers that use pickle with our library. We must support both use cases.

As a simple example, using `pickle` OR `asdict` with `json.dumps` on
```py
class Example:
      value: ElementModQ
```
should serialize to and deserialize from
```json
{
    "value": 123
}
```

**Comment by ronnie-llamado** [comment]
After working on this for a bit, here's some notes on the issue. A lot of this is already said in the top of the thread, but this is just breaking it down further for myself and anyone else following along.

---

### Method 1: Inheriting from `int` and overriding existing functions

#### Pros:
1. `json` will be able to serialize without extra work/arguments. The `json` module (with the default encoder) only serializes  `str`, `NoneType`, `bool`, `int`, and `float`. By subclassing `int`, `json` will support serialization  of `BaseElement` without the use of a custom encoder. (For deserialization: see Method 1, Con 2)

#### Cons:
1. Requires redefining all mathematical dunder methods. This work is not difficult, but tedious. There may be bugs if a function is not redefined as it will likely return an `int` type (and therefore lose the desired bounded limits).

For every supported method, the parent method will need to be called and then cast as `ElementModP`/`ElementModQ`.
```python
    def __add__(self, other):
        """a + b"""
        if isinstance(other, (self.__class__, int)):
            value = super().__add__(other)
            return self.__class__(value)
        
        return NotImplemented
```
For every unsupported method, there will need to be a TypeError raised. Since `BaseElement` would subclass `int`, it will fallback to parent methods and return an `int` if not redefined.
```python
    def __lshift__(self, other):
       """a << b"""
       raise TypeError(f"unsupported operand type(s) for <<: 'BaseElement' and {other.__class__.__name__}")
```

2. If a `json` deserialized object needs to retain bounded limits for future operations, a custom encoder/decoder will be required. By default, all integers are cast as `int` in `json.loads` (unless specified by a `parse_int` argument). However, there will be no way to determine if an integer is of type `int`, `ElementModP`, or `ElementModQ`.
```python
>>> unmodified = ElementModQ(1)
>>> deserialized = json.loads(json.dumps(unmodified))
>>> unmodified + ElementModQ.get_upper_bound()  # should throw OverflowError and will
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ronnie/Projects/electionguard-python/src/electionguard/group.py", line 80, in __add__
    return self.__class__(value)
  File "/home/ronnie/Projects/electionguard-python/src/electionguard/group.py", line 54, in __new__
    raise OverflowError(elem, cls.get_upper_bound())
OverflowError: (115792089237316195423570985008687907853269984665640564039457584007913129639748, 115792089237316195423570985008687907853269984665640564039457584007913129639747)
>>> deserialized + ElementModQ.get_upper_bound()  # should throw OverflowError and will not
115792089237316195423570985008687907853269984665640564039457584007913129639748
>>> print(type(unmodified))
<class 'electionguard.group.ElementModQ'>
>>> print(type(deserialized))
<class 'int'>
```

---

### Method 2: Creating custom numeric type

#### Pros:
1. `int` will not interact with `BaseElement` unless the behavior is defined in `BaseElement`. There will be no need to raise `TypeError` in all unsupported methods like in Method 1, Con 1. There will be no holes left behind for any bugs; if the behavior is not defined, it will not happen.

#### Cons:
1. `json` will not be able to de/serialize without a custom decoder/encoder (or added dependency such as `jsons`). 

2. Extra logic will need to be included to support serialization by `pickle`(`__getnewargs__`), and `pydantic`(`__get_validators__`).`

---

### Final Thoughts

If `BaseElement` is only serialized once (and only deserialized to verify equality), then Method 1 is preferred. There will be no custom encoder/decoders or code required to support `json`, `pickle`, or `pydantic`.

If `BaseElement` will be interacted with after deserializing and serializing, a custom encoder/decoder will be required. This would make Method 2 preferable, as there is no chance of leaving any of the inherited `int` methods not redefined.

**Comment by ronnie-llamado** [comment]
@keithrfung Piggybacking on the final thoughts from above, do you know if `ElementModP`/`ElementModQ` are only deserialized to verify equality? Or will operations be performed on the deserialized objects (so they'll need to retain their limits of [0,P/Q) )?

I have the changes to Method 1 queued up locally for #487, if that pivot is necessary.

**Comment by keithrfung** [comment]
@ronnie-llamado I saw this. This was extremely thorough. Thanks for running through the options. You missed the community call today. I will discuss this with the team tomorrow.

**Comment by danwallach** [comment]
One thought: if the choice is about making it easier to do serialization versus making everything else easier, that's a strong argument in favor of Option 2 (custom type unrelated to int).

Fwiw, supporting pickle, which I needed for arlo-cvr-encryption, required four lines of code: two serializes and two deserializers. Very straightforward. Also avoids the risk of getting a JSON integer for a bignum, which will explode in some programming languages. 

One other thought: Python is unusual in allowing you to subclass the int built-in. That's not legal in Java, where int isn't a class type, and Integer is (I think) final. I suspect many other programming languages put similar restrictions on performance-sensitive types like this. Why does this matter? Our Python code is supposed to be a "reference" implementation, which means we expect this code to be transliterated into many other programming languages. That was the reason I initially used only top-level functions and NamedTuples -- because every programming language, from C on up, has features like that. I wanted to avoid as many Python-specific quirks as possible. I still think this is an important attribute for "reference" code.

**Comment by keithrfung** [comment]
There's a level where we need to separate how languages handle different problems. This isn't just a `pickle` or just `asdict` but what an `Element` actually is. The concern for serialization to JSON is valid, but this can also sit outside `electionguard` as a  library. 

At the core of it, the `Element` is just an `int` that we add specific math functions to. Other libraries will be handling this value with their equivalent of big int (such as `BigInteger` in Java) which will likely also involve some variation. Likely some of them have different implementation of modulus math that won't be using `gmp`. I think there are less python quirks than it may seem. 

I think this comes down to overall architecture. The move to int subclassing was to remove custom serialization at the bottom level of python. The stack currently depends on this. The moves to create this would mean moving a lot more furniture than simply adding a dataclasses and should be looked at more holistically. For example, creating an entire list of specifically serializable classes like POCO's and being able to convert to those.

**Comment by keithrfung** [comment]
@ronnie-llamado 

In your example, Method 1 Note 2 is missing something. We had to do this previously. This must include the cast. json will actually defaultly make it an untyped dictionary. This is also true for dataclasses.
```py
json.loads(json.dumps(unmodified), ElementModQ)
```

**Comment by danwallach** [comment]
Also worth noting: one possible future direction for ElectionGuard is moving from ElGamal over integers to some sort of elliptic curve implementation. So, saying that "an Element is just an int" is just an accident of the current design. It could well be a tuple of two numbers, or it could be something else entirely.

I'm still opposed to subclassing `int`. An Element is a key, or a ciphertext, but it's only incidentally a number, and I'm very much interested in preserving our ability to use the static type system to ensure that we don't accidentally mistake one for the other.
