### ISSUE TITLE
✨ Misc issues with JSON serialization in 1.4.0

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

1. SubmittedBallot.state: BallotBoxState is encoded as a number. Recommend that it be the name of the enum to remove ambiguity and language dependence.
   - 0 or 1 based? 
   - only place that indicates whether the ballot is cast or spoiled. 
   - Would be disastrous for this to be misinterpreted.

2. boolean values are encoded sometimes as "00" or "01" or null or true or false. Recommend true or false for clarity.
  - where the field is bool, eg CiphertextBallotSelection.is_placeholder_selection, it is encoded as "00" or "01".
  - where the field is Optional[bool] , eg Manifest.Candidate.is_write_in, is encoded as null or true or false.
  - also recommend not using Optional for fields to be serialized, or encode null as false.

3. Integers (32 or 64 bit) are encoded as hex strings. Recommend they be encoded as integers for clarity.

4. SubmittedBallot serialization carries nonce fields, but these must be null. Consider not serializing them.

5. A serialization version number could allow smooth upgrading, and prevent silent failures of processing the election record. Consider adding that to CiphertextElectionContext.

**Comment by rc-ms** [comment]
Thanks for submitting @JohnLCaron. These are excellent requests. Most of the team is taking a week off; I will triage this with them and get back to you when we'll be able to slot the fixes

**Comment by keithrfung** [comment]
@rc-ms These should be isolated out into separate issues. This should stay in `triage` until that's done. Then this card can be deleted after. Some of these based on my open PR may change as well. I will answer all of them here for brevity

1. I agree with this, as I think will most of the team. Previous enums we handled with strings like the reasons in the proofs. This lines up. 

2. I believe there is reasoning for why these were `0` and `1` instead of true or false which has to do with their use in tallies. This being said, there should be a bug for the `00` and `01` issue.

3. This was due to a larger problem and should be irrelevant with my current PR. Long term, ElectionGuard 2.0 we should revisit this problem.

4. Not so much an issue, but I think with using the different serialization tool we can handle this. There is a setting for this. 
https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeldict
See `exclude_unset`

5. There is a solution for this already. It is supposed to be the specification number that is in the Manifest. The issue has been we have been shifting too much before locking in to a Specification. 1.0 technically is not standardized at this current juncture.

**Comment by rc-ms** [comment]
thanks @keithrfung will do so just signalling this work should be done as part of EG 1.0 release

**Comment by JohnLCaron** [comment]
Made separate issue #531 for serialization version number

**Comment by JohnLCaron** [comment]
Made separate issue #532 for serialization of booleans

**Comment by keithrfung** [comment]
@JohnLCaron Have I ever told you how much I appreciate you? Thanks for being on top of stuff.

**Comment by keithrfung** [comment]
Made isolated issues sitting at top level to resolve outside of python first.
