### ISSUE TITLE
🐍 Support Python 3.10 by unlocking version of gmpy2

### ISSUE THREAD

**Issue by thommignot** [microsoft/electionguard-python#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Actually the version of the gmpy2 package required by electionguard-python (2.0.8) is not compatible with Python 3.10 (see https://github.com/aleaxit/gmpy/pull/297 )

This error prevent from building wheels for gmpy2
`  ERROR: Failed building wheel for gmpy2`

### Steps To Reproduce

Try to install electionguard-python in a python 3.10 env.

### Environment

```markdown
-OS: Archlinux
-Python version: 3.10
```

### Anything else?

Why is 2.0.8 required ? Is there another (newer) version that could work or should I just downgrade the python version?

I think it's better to always target newer python versions, in addition that latests versions of gmpy includes binary wheels for various platforms.

I know that the README says that python 3.9 is *required* but I'm able to run this package with python 3.10 and gmpy2==2.1.2 without any problem (all tests pass) on up-to-date Archlinux so I thought it was required at the time it was written, but the version is fixed by `pyproject.toml`

**Comment by keithrfung** [comment]
We currently intentionally lock the version because the python version vs gmpy version tends to be a bit of a conundrum. 

It's a bit unfair to new developers. We had the issues with both python 3.8 & python 3.9.7 and the gmpy version they line up with. The current version is locked to 3.9 and 3.08 because this is the prebuilt packages we provide for building on windows. 

But yes, this isn't so much a bug as a request for an enhancement. Relabeling.
https://github.com/microsoft/electionguard-python/blob/e35b68dc3175243ffaf872e9a0ea56c5b8a05830/README.md?plain=1#L38

**Comment by keithrfung** [comment]
Marking this as `blocked` until there is an internal meeting discussing this move. If we can automate the Windows build and keep an easy installation on this side we can revert to having the version more flexible.
