### ISSUE TITLE
♻️  Refactor Words to line up better with ElectionGuard 1.0 Specification

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

There are likely more words but one concern is that there are a couple key phrases that are confusing with the current specification. The goal is to refactor as minimally as possibly yet get closer to the specification wording. 

*Election Public Key** is a problematic phrase. The current python considers each of the keys the guardians combines as an election public key. These are unnamed in the specifications, however the election public key is used to describe the combined key used for encryption the election. This leads to difficulties surrounding the key shares (as referred to in specification) and the election partial key backups (as referred to in python). This is reduced substantially because of the removal of auxiliary keys and the need for guardians to have two different keys. 

### Possible Implementation

The main area of focus would be the Key Ceremony. 

The main refactors as denoted so far are:
`ElectionPublicKey` -> `GuardianKey` or `guardian_key` for parameters
`ElectionKeyPair` -> `GuardianKeyPair` or `guardian_key_pair` for parameters
`ElectionJointKey` -> `ElectionKey` or `election_key` for parameters
`ElectionPartialKeyVerification` -> `KeyShareVerification` or `verification` for parameters
`ElectionPartialKeyChallenge` -> `KeyShareChallenge` or `challenge` for parameters

Methods would be updated accordingly. 
The major piece is replacing `election_key_pair` -> `guardian_key_pair`

For example:
https://github.com/microsoft/electionguard-python/blob/c14758bc67ebbcdeb4f98958fbe4e0b0310a20f1/src/electionguard/key_ceremony.py#L268-L288

Refactored to
```py
def combine_guardian_keys(
    guardian_keys: List[GuardianKey],
) -> ElectionKey:
    public_keys = [set.key for set in guardian_keys]
    commitments = [
        commitment
        for set in guardian_keys
        for commitment in set.coefficient_commitments
    ]

    return ElectionKey(
        joint_public_key=elgamal_combine_public_keys(public_keys),
        commitment_hash=get_optional(
            hash_elems(commitments)
        ),  # H(K 1,0 , K 2,0 ... , K n,0 )
    )
```

### Anything else?

There may be other pieces to revisit. 

The major files should be 
`key_ceremony.py` and `guardian.py`

**Comment by benaloh** [comment]
Any of "ElectionKey", "ElectionPublicKey", or "ElectionJointKey" should be fine for the primary key used to encrypt all ballots.  It seems somewhat unnatural to have Guardian keys under the Election Key because the Guardian keys are generated independently prior to the establishment of the Election Key.

**Comment by keithrfung** [comment]
@benaloh I think there may have been some confusion. I'm gonna try to reword. 

Currently:
Each `Guardian` has an ElectionPublicKey from their ElectionPublicKeyPair 
All the `ElectionPublicKey`s combine to create `ElectionJointKey`


Suggested:
`Guardian` has a `GuardianKey` from their `GaurdianKeyPair`
All the `GuardianKey`s combine to create `ElectionKey`

**Comment by benaloh** [comment]
I'm concerned that "GuardianKey" is ambiguous since each guardian has two keys.  "GuardianPublicKey" and "GuardianPrivateKey" (or "GuardianEncryptionKey" and "GuardianDecryptionKey") seem fine.  Since there is no single election private/decryption key, there is no ambiguity in using the simpler term "ElectionKey".

**Comment by keithrfung** [comment]
That's fair. This is partially the reason I wanted to shift away from public and private.

**Comment by benaloh** [comment]
I think that either "GuardianPublicKey" and "GuardianPrivateKey" or "GuardianEncryptionKey" and "GuardianDecryptionKey" works here.  The former might be a bit better because guardian public/encryption keys are never used to encrypt votes (only internal communications) and instead their principal purpose is to construct the election key.  So the question of "What does a "GuardianEncryptionKey" encrypt?" might be difficult to answer.

**Comment by colleenirt** [comment]
This will not be worked or considered for 1.0.  A new issue will be created if needed in the future.
