### ISSUE TITLE
♻️  Refactor CLI print functions 

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

The CLI includes some printing function that are currently in a base step but could be isolated completely to a set of printer functions. 

https://github.com/microsoft/electionguard-python/blob/8aa589c9744bdf52e1e2659e2f83c255ffc65441/src/electionguard_cli/e2e_steps/e2e_step_base.py#L5

https://github.com/microsoft/electionguard-python/blob/main/src/electionguard_cli/e2e_steps/print_results_step.py

### Possible Implementation

A simpler implementation that is a bit more pythonic is shifting to make a printer module for the CLI. This could include some standard color coding for different sections. That could be changed.

```py
header_color = "green"
description_color = "white"

def print_header(header:str) -> None:
    ...
```

The base step can be removed and instead methods can just be imported directly as they are used. The name `printer_tools` is just an example. 

from electionguard_cli.printer_tools import print_header

**Comment by phershbe** [comment]
@keithrfung I'm digging into the code and the issues in order to contribute more. I think I'm understanding this. The file that you have referenced above is from a branch, and the file is now here: https://github.com/microsoft/electionguard-python/blob/main/src/electionguard_cli/cli_steps/cli_step_base.py and color coding has been added but a printer module has not been added yet, correct?

**Comment by keithrfung** [comment]
Duplicate of #601
