### ISSUE TITLE
🏎  Encrypt default should set proof verification to False

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Adjust `should_verify_proofs` to `False` as the default for the encrypt functions to allow for speed as opposed to thoroughness for default production system. This is to match the expectations on the C++ side as well. 

### Possible Implementation

The following lines would need to be updated:
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L161
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L243
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L412
https://github.com/microsoft/electionguard-python/blob/ec69dec9cc802824ba37d273b3ffebdf7f6af9fc/src/electionguard/encrypt.py#L496

Tests outside of bench for `encrypt` should also always ensure to pass True into these functions for `should_verify_proof`. Be sure to adjust comments where it mentions default is True.

**Comment by phershbe** [comment]
I'm pretty new to open source but am confident enough in my skills. I can work on this if you need. Adjusting the tests will be something new for me, I think I'll be okay though.
Also, in the part at the bottom about tests, it says "Tests outside of bench for encrypt should also always ensure to pass True into these functions for should_verify_proof. Be sure to adjust comments where it mentions default is True." ... Is this supposed to be "also always ensure to pass False into these functions"?

**Comment by keithrfung** [comment]
@phershbe No, in the tests we want to pass true to ensure the proofs verify. In production based systems, it's overkill to verify the proofs every time.

**Comment by keithrfung** [comment]
Also, @phershbe take a crack at it.

**Comment by phershbe** [comment]
So in https://github.com/microsoft/electionguard-python/blob/ef6ce802b107fbd95e12eafad0a3f46f552574fd/tests/property/test_encrypt.py there are three instances of should_verify_proofs ... two are False and one is True. Should those all be set to True?

**Comment by keithrfung** [comment]
No. I would keep the `should_verify_proofs` states as they are there.

**Comment by phershbe** [comment]
@keithrfung No problem on the reply, I forgot to tag you initially as well. So since you said to keep the should_verify_proofs states as they were, then what does the following below mean?
"Tests outside of bench for encrypt should also always ensure to pass True into these functions for should_verify_proof. Be sure to adjust comments where it mentions default is True."
Because I can't find any other should_verify_proof or should_verify_proofs in the tests.
I understand changing the comments.
Thank you for your patience, I'm learning a lot and want to keep contributing after this if I can understand enough because the project is really cool. I'll make the changes after this.

**Comment by keithrfung** [comment]
@phershbe 

I'm discussing the actual functions that had parameters changed such as this `encrypt_selection`. This can't be found by direct references off `should_verify_proofs`.

Items like this in the tests
https://github.com/microsoft/electionguard-python/blob/ef6ce802b107fbd95e12eafad0a3f46f552574fd/tests/property/test_encrypt.py#L80-L83

Should be 
```py
       result = encrypt_selection(
            subject, metadata, keypair.public_key, ONE_MOD_Q, nonce, should_verify_proofs = True
        )
```

**Comment by phershbe** [comment]
@keithrfung Okay, awesome, thank you. I will get the pull request in soon.

**Comment by phershbe** [comment]
@keithrfung Thank you for your patience. I wanted to do my best since I hadn't really done a pull request on anything other than HTML before, and I was learning more about tests, and taxes were due. The pull request describes what I did. Hopefully I didn't do too badly, I would like to keep digging in and understanding the project more and contributing if I can understand enough to help.
